### ISSUE TITLE
find MPI

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/Latte.jl#2]
CMake has a lot of issues finding mpi wrapper. Latte should probably just check for `CC` (Cray wrapper), `mpiicpc` (Intel MPI), and `mpic++` (MPICH).

**Comment by leonardt** [comment]
I think the current best/easiest solution to this is to rely on the user specified CC and CXX env vars if Cmake can't pick it up automatically.  Something like `CC=mpiicc CXX=mpiicpc cmake ..` seems to be pretty reliable
